### PR TITLE
Added 3 new LOBSTR nodes

### PR DESCRIPTION
**Pull request by pitsevich**

### CODE REVIEW

**Comment by tomerweller** [comment]
@pitsevich can you add these to your toml file? (https://lobstr.co/.well-known/stellar.toml)

**Comment by pitsevich** [comment]
@tomerweller Thanks, done. 
Was not expecting you to review this before we pushed the updates today :)

**Comment by pitsevich** [comment]
Lobstr V3:
https://stellarbeat.io/quorum-monitor/GD5QWEVV4GZZTQP46BRXV5CUMMMLP4JTGFD7FWYJJWRL54CELY6JGQ63?center=1

Lobstr V4:
https://stellarbeat.io/quorum-monitor/GA7TEPCBDQKI7JQLQ34ZURRMK44DVYCIGVXQQWNSWAEQR6KB4FMCBT7J?center=1

Lobstr V5:
https://stellarbeat.io/quorum-monitor/GA5STBMV6QDXFDGD62MEHLLHZTPDI77U3PFOD2SELU5RJDHQWBR5NNK7?center=1

**Comment by pitsevich** [comment]
@tomerweller let me know if there's anything else that we're missing

**Pull request merged**
