### PR TITLE
Jest tests added

### PR DESCRIPTION
**Pull request by davolokh**
- Tests added. [Jest](https://facebook.github.io/jest/) used.
- Two tests were written as example.

Dependencies changes
*package.json:*
```
"jest": "^22.3.0",
"react": "16.2.0",
"react-test-renderer": "^16.2.0"
```

Should I implement full test coverage?
Btw, Jest allows to build coverage reports. Example below.
screen shot 2018-02-15 at 9 01 24 pm

### CODE REVIEW

**Comment by davolokh** [comment]
@jedmccaleb @bartekn 
Does this look reasonable?

**Comment by jedmccaleb** [comment]
Thanks. Why did you close it?

**Comment by davolokh** [comment]
Closed by mistake. Got a green light about it?

**Comment by poliha** [comment]
Hey @davolokh thanks for working on this. These test will be useful.
Can you keep working on this and hopefully add some comments with the tests for those of us not familiar with Jest? 
Thanks

**Comment by dangdennis** [comment]
I highly recommend [react-testing-library](https://github.com/testing-library/react-testing-library) (RTL) for unit testing. There's a lot to be said about testing UI, but RTL tests functionality, versus implementation details.

**Pull request closed without merging**
