### PR TITLE
dashboard: add failed tx chart

### LINKED ISSUE #73: add failed transactions to graphs
https://github.com/stellar/go/pull/756

### PR DESCRIPTION
**Pull request by poliha**
Added a new chart that shows the number of failed and successful transactions in the last 100 ledgers.
Closes #73

### CODE REVIEW

**Comment by bartekn** [comment]
@poliha is it ready for review? It doesn't seem to work in [netify preview](https://deploy-preview-79--friendly-leakey-52f4da.netlify.com/). I also pulled the code and it doesn't work locally.

**Comment by poliha** [comment]
Yes @bartekn Its ready. I think the issue is with the the monitoring horizon server.. it needs to be updated

**Comment by bartekn** [comment]
LGTM! Just 2 comments:
- Can we make this stacked? I think it will be easier to read.
- Can you add the same chart for testnet?

**Comment by poliha** [comment]
This is stacked now. Also added the chart for testnet and reduced set `limit=100` for ledgers retrieved from horizon. This improves the visibility of the chart

**Pull request merged**
